#!/bin/bash
git add .
BRANCH=$(git rev-parse --abbrev-ref HEAD)
echo "💡 Текущая ветка: $BRANCH"
# 1. Выполняем git pull и git pull --recurse-submodules
echo "🔄 Выполняем git pull"

git fetch
git pull $BRANCH

echo "🔄 Запуск Prettier для изменённых файлов..."

# Получаем изменённые файлы (индексированные для коммита)
FILES=$(git diff --name-only --cached --diff-filter=d | grep -E '\.(js|jsx|ts|tsx|json|css|scss|md|html)$')

if [ -n "$FILES" ]; then
    # Запускаем Prettier
    npx prettier --write $FILES
    echo "✅ Prettier применён."

    # Добавляем файлы обратно в индекс
    git add $FILES
else
    echo "💡 Нет файлов для форматирования."
fi

echo "✅ Ошибок нет."
exit 0

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --type=bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff-index --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --